server:
  port: 8082

framework:
  connectors:
    rest:
      enabled: true
      authMode: ldap
  routing:
    - processName: "ldap-auth-process"
      triggers:
        - type: "rest"
          path: "/auth/ldap"
          method: "POST"
