server:
  port: 8082

framework:
  connectors:
    rest:
      enabled: true
      authMode: ldap
  routing:
    - processName: "ldap-auth-process"
      triggers:
        - type: "rest"
          path: "/auth/ldap"
          method: "POST"

spring:
  ldap:
    embedded:
      base-dn: dc=springframework,dc=org
      ldif: classpath:users.ldif
      port: 8389 # Default LDAP port for embedded server
