spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

framework:
  connectors:
    rest:
      enabled: true
      authMode: bypass
    kafka:
      enabled: false
      bootstrap-servers: "localhost:9092"
  routing:
    - processName: "echo-service"
      triggers:
        - type: "rest"
          path: "/api/echo"
          method: "POST"
  security:
    self-signed-cert:
      enabled: true

server:
  port: 8443  # HTTPS port
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: selfsigned
    # Force HTTPS only - redirect HTTP to HTTPS
  http2:
    enabled: true

# Disable HTTP connector - HTTPS only
management:
  server:
    port: 8444
    ssl:
      enabled: true

my:
  secret:
    property: ENC(i2f5sJmGgP6yqBPnM+2LCA==)
