server:
  port: 8081

spring:
  application:
    name: basic-auth-rest
  
  datasource:
    url: jdbc:h2:mem:basicauthrestdb
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  # Thyme leaf template configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

framework:
  adapters:
    rest:
      enabled: true
      authMode: basic
  security:
    self-signed-cert:
      enabled: false

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    blog.eric231.examples.basicauthrest: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"