server:
  port: 8085
  ssl:
    enabled: true
    key-store: classpath:mtls-keystore.p12
    key-store-password: mtlspass
    key-store-type: PKCS12
    key-alias: mtls-server
    client-auth: need
    trust-store: classpath:mtls-truststore.p12
    trust-store-password: mtlspass
    trust-store-type: PKCS12

spring:
  datasource:
    url: jdbc:h2:mem:mtlsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

framework:
  connectors:
    rest:
      enabled: true
      authMode: mtls
  routing:
    - processName: "mtls-auth-process"
      triggers:
        - type: "rest"
          path: "/auth/mtls"
          method: "GET"
    - processName: "certificate-management-process"
      triggers:
        - type: "rest"
          path: "/api/certificates"
          method: "GET"
    - processName: "certificate-register-process"
      triggers:
        - type: "rest"
          path: "/api/certificates"
          method: "POST"

logging:
  level:
    org.springframework.security: DEBUG
    blog.eric231: DEBUG
